### ISSUE TITLE
No map while sharing location

### ISSUE THREAD

**Issue by kswt** [Telegram-FOSS-Team/Telegram-FOSS#309]
I see it when I try share location or view location shared by anoter person.
![Screenshot_20190320-193519](https://user-images.githubusercontent.com/17752333/54702364-c3212000-4b47-11e9-95cb-bc729e1deff8.png)

**Comment by Bubu** [comment]
This is solved in Version 5.4. You can manually upgrade to it from f-droid right now, or wait another day for it to be suggested automatically.

**Comment by kswt** [comment]
> This is solved in Version 5.4. You can manually upgrade to it from f-droid right now, or wait another day for it to be suggested automatically.
 I installed the latest version from Releases, but problem is not solved.
